/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hiroshi' at '16/10/08 21:58' with Gradle 2.0
 *
 * @author hiroshi, @date 16/10/08 21:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
